const CartActionTypes = {
  ADD_CARTITEM: "ADD_CARTITEM",
  GET_CARTITEM: "GET_CARTITEM",
  GET_CARTITEM_SUCCESS: "GET_CARTITEM_SUCCESS",
  GET_CARTITEM_FAILURE: "GET_CARTITEM_FAILURE",
  COUNT_CARTITEM: "COUNT_CARTITEM",
  REMOVE_CARTITEM: "REMOVE_CARTITEM",
};

export default CartActionTypes;
